name: Lint, Test & Deploy
on: workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Output GitHub Context
        run: echo "${{ toJSON(github.event.issue) }}"
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: npm run test
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        run: npm run build